name: Release

on:
  # Run the workflow each time new commits are pushed to the candidate branch. 
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  screenshots:
    name: 📸 Gather screenshots
    runs-on: ubuntu-latest
    steps:
      - name: 📸 Gather screenshots
        uses: snapcrafters/ci/get-screenshots@main
        with:
          issue-number: "123"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          screenshots-token: "random-string"
      - name: Check if previous step failed
        if: ${{ failure() && steps.screenshot_step.outcome == 'failure' }}
        run: |
          echo "Gathering screenshots failed. Entering debug mode..."
          # You can add additional commands here to handle the failure as needed
      
      - name: Setup upterm session
        if: ${{ always() }} # This ensures that the upterm session is set up regardless of previous step success or failure
        uses: lhotari/action-upterm@v1