name: Release

on:
  # Run the workflow each time new commits are pushed to the candidate branch. 
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  screenshots:
    name: 📸 Gather screenshots
    runs-on: ubuntu-latest
    steps:
      - name: 📸 Gather screenshots
        uses: snapcrafters/ci/get-screenshots@main
        with:
          issue-number: "123"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          screenshots-token: "random-string"
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
